// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528114245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Complement")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MainNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("NeighborhoodId")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("StreetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TertiaryNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("AddressId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("StreetTypeId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Audit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("AffectedEntity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AffectedRecordId")
                        .HasColumnType("int");

                    b.Property<int>("AuditActionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditActionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Audits", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AuditActionType", b =>
                {
                    b.Property<int>("AuditActionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditActionTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AuditActionTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuditActionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            AuditActionTypeId = 1,
                            Name = "CREATE"
                        },
                        new
                        {
                            AuditActionTypeId = 2,
                            Name = "UPDATE"
                        },
                        new
                        {
                            AuditActionTypeId = 3,
                            Name = "DELETE"
                        },
                        new
                        {
                            AuditActionTypeId = 4,
                            Name = "CANCEL"
                        },
                        new
                        {
                            AuditActionTypeId = 5,
                            Name = "VOID"
                        },
                        new
                        {
                            AuditActionTypeId = 6,
                            Name = "LOGIN"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CardType", b =>
                {
                    b.Property<int>("CardTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CardTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CardTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CardTypes", (string)null);

                    b.HasData(
                        new
                        {
                            CardTypeId = 1,
                            Name = "Visa"
                        },
                        new
                        {
                            CardTypeId = 2,
                            Name = "Mastercard"
                        },
                        new
                        {
                            CardTypeId = 3,
                            Name = "AmericanExpress"
                        },
                        new
                        {
                            CardTypeId = 4,
                            Name = "Debit"
                        });
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CityId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CityId");

                    b.HasIndex("DepartmentId", "Name")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            DepartmentId = 1,
                            Name = "Bucaramanga"
                        },
                        new
                        {
                            CityId = 2,
                            DepartmentId = 1,
                            Name = "Floridablanca"
                        },
                        new
                        {
                            CityId = 3,
                            DepartmentId = 1,
                            Name = "Giron"
                        },
                        new
                        {
                            CityId = 4,
                            DepartmentId = 2,
                            Name = "Bogota"
                        },
                        new
                        {
                            CityId = 5,
                            DepartmentId = 3,
                            Name = "Medellin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Colombia",
                            PhoneCode = "+57"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Venezuela",
                            PhoneCode = "+58"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Ecuador",
                            PhoneCode = "+593"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CountryId = 1,
                            Name = "Santander"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CountryId = 1,
                            Name = "Cundinamarca"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CountryId = 1,
                            Name = "Antioquia"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("DocumentTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DocumentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            DocumentTypeId = 1,
                            Code = "CC",
                            Name = "Cedula de Ciudadania"
                        },
                        new
                        {
                            DocumentTypeId = 2,
                            Code = "NIT",
                            Name = "NIT"
                        },
                        new
                        {
                            DocumentTypeId = 3,
                            Code = "CE",
                            Name = "Cedula de Extranjeria"
                        },
                        new
                        {
                            DocumentTypeId = 4,
                            Code = "PAS",
                            Name = "Pasaporte"
                        });
                });

            modelBuilder.Entity("Domain.Entities.EmailDomain", b =>
                {
                    b.Property<int>("EmailDomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmailDomainId"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmailDomainId");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("EmailDomains", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("GenderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genders", (string)null);

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            Name = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            Name = "Female"
                        },
                        new
                        {
                            GenderId = 3,
                            Name = "Other"
                        },
                        new
                        {
                            GenderId = 4,
                            Name = "PreferNotToSay"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("InvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("InvoiceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("InvoiceStatusId");

                    b.HasIndex("ServiceOrderId")
                        .IsUnique();

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceDetailId"));

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("SourcePartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceDetailId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SourcePartId");

                    b.ToTable("InvoiceDetails", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InvoiceStatus", b =>
                {
                    b.Property<int>("InvoiceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("InvoiceStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InvoiceStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            InvoiceStatusId = 1,
                            Name = "Draft"
                        },
                        new
                        {
                            InvoiceStatusId = 2,
                            Name = "Issued"
                        },
                        new
                        {
                            InvoiceStatusId = 3,
                            Name = "Paid"
                        },
                        new
                        {
                            InvoiceStatusId = 4,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MechanicAssignment", b =>
                {
                    b.Property<int>("MechanicAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MechanicAssignmentId"));

                    b.Property<int>("MechanicPersonId")
                        .HasColumnType("int");

                    b.Property<int>("OrderServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("MechanicAssignmentId");

                    b.HasIndex("MechanicPersonId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("OrderServiceId", "MechanicPersonId")
                        .IsUnique();

                    b.ToTable("MechanicAssignments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MechanicSpecialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SpecialtyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MechanicSpecialties", (string)null);

                    b.HasData(
                        new
                        {
                            SpecialtyId = 1,
                            Name = "Engine"
                        },
                        new
                        {
                            SpecialtyId = 2,
                            Name = "Electrical"
                        },
                        new
                        {
                            SpecialtyId = 3,
                            Name = "AirConditioning"
                        },
                        new
                        {
                            SpecialtyId = 4,
                            Name = "Suspension"
                        },
                        new
                        {
                            SpecialtyId = 5,
                            Name = "Brakes"
                        },
                        new
                        {
                            SpecialtyId = 6,
                            Name = "GeneralDiagnostics"
                        },
                        new
                        {
                            SpecialtyId = 7,
                            Name = "Bodywork"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MechanicSpecialtyAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("PersonId", "SpecialtyId")
                        .IsUnique();

                    b.ToTable("MechanicSpecialtyAssignments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Neighborhood", b =>
                {
                    b.Property<int>("NeighborhoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NeighborhoodId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("NeighborhoodId");

                    b.HasIndex("CityId");

                    b.ToTable("Neighborhoods", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderService", b =>
                {
                    b.Property<int>("OrderServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderServiceId"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("CustomerApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("LaborCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("WorkPerformed")
                        .HasColumnType("text");

                    b.HasKey("OrderServiceId");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("OrderServices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderServicePart", b =>
                {
                    b.Property<int>("OrderServicePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderServicePartId"));

                    b.Property<decimal>("AppliedUnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("CustomerApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrderServiceId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OrderServicePartId");

                    b.HasIndex("PartId");

                    b.HasIndex("OrderServiceId", "PartId")
                        .IsUnique();

                    b.ToTable("OrderServiceParts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OrderStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OrderStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            OrderStatusId = 2,
                            Name = "InProgress"
                        },
                        new
                        {
                            OrderStatusId = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            Name = "Cancelled"
                        },
                        new
                        {
                            OrderStatusId = 5,
                            Name = "Voided"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("OrderStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("NewOrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<int?>("PreviousOrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.HasKey("OrderStatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("NewOrderStatusId");

                    b.HasIndex("PreviousOrderStatusId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("OrderStatusHistory", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int?>("PartBrandId")
                        .HasColumnType("int");

                    b.Property<int>("PartCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PartId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PartBrandId");

                    b.HasIndex("PartCategoryId");

                    b.ToTable("Parts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PartBrand", b =>
                {
                    b.Property<int>("PartBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PartBrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("PartBrandId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartBrands", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PartCategory", b =>
                {
                    b.Property<int>("PartCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PartCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PartCategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartCategories", (string)null);

                    b.HasData(
                        new
                        {
                            PartCategoryId = 1,
                            Name = "Filters"
                        },
                        new
                        {
                            PartCategoryId = 2,
                            Name = "Oils and Lubricants"
                        },
                        new
                        {
                            PartCategoryId = 3,
                            Name = "Brakes"
                        },
                        new
                        {
                            PartCategoryId = 4,
                            Name = "Suspension"
                        },
                        new
                        {
                            PartCategoryId = 5,
                            Name = "Electrical"
                        },
                        new
                        {
                            PartCategoryId = 6,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            PartCategoryId = 7,
                            Name = "Engine"
                        },
                        new
                        {
                            PartCategoryId = 8,
                            Name = "Bodywork"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PartPurchase", b =>
                {
                    b.Property<int>("PartPurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PartPurchaseId"));

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("PartPurchaseId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PartPurchases", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PartPurchaseDetail", b =>
                {
                    b.Property<int>("PartPurchaseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PartPurchaseDetailId"));

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("PartPurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PartPurchaseDetailId");

                    b.HasIndex("PartId");

                    b.HasIndex("PartPurchaseId", "PartId")
                        .IsUnique();

                    b.ToTable("PartPurchaseDetails", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentStatusId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PaymentCard", b =>
                {
                    b.Property<int>("PaymentCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentCardId"));

                    b.Property<string>("AuthorizationCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LastFourDigits")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("PaymentCardId");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("PaymentCards", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PaymentMethods", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentMethodId = 1,
                            Name = "Cash"
                        },
                        new
                        {
                            PaymentMethodId = 2,
                            Name = "Card"
                        },
                        new
                        {
                            PaymentMethodId = 3,
                            Name = "BankTransfer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PaymentStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentStatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            PaymentStatusId = 2,
                            Name = "Completed"
                        },
                        new
                        {
                            PaymentStatusId = 3,
                            Name = "Refunded"
                        },
                        new
                        {
                            PaymentStatusId = 4,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PersonId");

                    b.HasIndex("AddressId");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("GenderId");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PersonEmail", b =>
                {
                    b.Property<int>("PersonEmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonEmailId"));

                    b.Property<int>("EmailDomainId")
                        .HasColumnType("int");

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonEmailId");

                    b.HasIndex("EmailDomainId");

                    b.HasIndex("PersonId");

                    b.HasIndex("EmailUser", "EmailDomainId")
                        .IsUnique();

                    b.ToTable("PersonEmails", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PersonPhone", b =>
                {
                    b.Property<int>("PersonPhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonPhoneId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PersonPhoneId");

                    b.HasIndex("PersonId");

                    b.HasIndex("CountryId", "PhoneNumber")
                        .IsUnique();

                    b.ToTable("PersonPhones", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PersonRole", b =>
                {
                    b.Property<int>("PersonRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonRoleId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PersonRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("PersonId", "RoleId")
                        .IsUnique();

                    b.ToTable("PersonRoles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Client"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Mechanic"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Receptionist"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ServiceOrder", b =>
                {
                    b.Property<int>("ServiceOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ServiceOrderId"));

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GeneralDescription")
                        .HasColumnType("text");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ServiceOrderId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceOrders", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<int>("EstimatedDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ServiceTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServiceTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ServiceTypeId = 1,
                            EstimatedDays = 1,
                            Name = "Preventive Maintenance"
                        },
                        new
                        {
                            ServiceTypeId = 2,
                            EstimatedDays = 3,
                            Name = "Mechanical Repair"
                        },
                        new
                        {
                            ServiceTypeId = 3,
                            EstimatedDays = 1,
                            Name = "Diagnostics"
                        },
                        new
                        {
                            ServiceTypeId = 4,
                            EstimatedDays = 2,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            ServiceTypeId = 5,
                            EstimatedDays = 2,
                            Name = "Electrical"
                        },
                        new
                        {
                            ServiceTypeId = 6,
                            EstimatedDays = 5,
                            Name = "Bodywork and Paint"
                        });
                });

            modelBuilder.Entity("Domain.Entities.StreetType", b =>
                {
                    b.Property<int>("StreetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StreetTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StreetTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StreetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            StreetTypeId = 1,
                            Name = "Calle"
                        },
                        new
                        {
                            StreetTypeId = 2,
                            Name = "Carrera"
                        },
                        new
                        {
                            StreetTypeId = 3,
                            Name = "Avenida"
                        },
                        new
                        {
                            StreetTypeId = 4,
                            Name = "Diagonal"
                        },
                        new
                        {
                            StreetTypeId = 5,
                            Name = "Transversal"
                        },
                        new
                        {
                            StreetTypeId = 6,
                            Name = "Circular"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("SupplierId");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("datetime");

                    b.HasKey("UserId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("Mileage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("year");

                    b.HasKey("VehicleId");

                    b.HasIndex("ModelId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleBrand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.ToTable("VehicleBrands", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleEntryInventory", b =>
                {
                    b.Property<int>("EntryInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EntryInventoryId"));

                    b.Property<bool>("HasScratches")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasToolbox")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<bool>("OwnershipCardDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ScratchesDescription")
                        .HasColumnType("text");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ToolboxDescription")
                        .HasColumnType("text");

                    b.HasKey("EntryInventoryId");

                    b.HasIndex("ServiceOrderId")
                        .IsUnique();

                    b.ToTable("VehicleEntryInventory", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ModelId");

                    b.HasIndex("BrandId", "ModelName")
                        .IsUnique();

                    b.ToTable("VehicleModels", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleOwnerHistory", b =>
                {
                    b.Property<int>("VehicleOwnerHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VehicleOwnerHistoryId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleOwnerHistoryId");

                    b.HasIndex("PersonId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleOwnerHistory", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("VehicleTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleTypes", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleTypeId = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            VehicleTypeId = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            VehicleTypeId = 3,
                            Name = "Pickup"
                        },
                        new
                        {
                            VehicleTypeId = 4,
                            Name = "Van"
                        },
                        new
                        {
                            VehicleTypeId = 5,
                            Name = "Motorcycle"
                        },
                        new
                        {
                            VehicleTypeId = 6,
                            Name = "Truck"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.HasOne("Domain.Entities.Neighborhood", "Neighborhood")
                        .WithMany("Addresses")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.StreetType", "StreetType")
                        .WithMany("Addresses")
                        .HasForeignKey("StreetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Neighborhood");

                    b.Navigation("StreetType");
                });

            modelBuilder.Entity("Domain.Entities.Audit", b =>
                {
                    b.HasOne("Domain.Entities.AuditActionType", "AuditActionType")
                        .WithMany("Audits")
                        .HasForeignKey("AuditActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Audits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditActionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Cities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("Departments")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.InvoiceStatus", "InvoiceStatus")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithOne("Invoice")
                        .HasForeignKey("Domain.Entities.Invoice", "ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvoiceStatus");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("Domain.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Part", "SourcePart")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("SourcePartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");

                    b.Navigation("SourcePart");
                });

            modelBuilder.Entity("Domain.Entities.MechanicAssignment", b =>
                {
                    b.HasOne("Domain.Entities.Person", "MechanicPerson")
                        .WithMany("MechanicAssignments")
                        .HasForeignKey("MechanicPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OrderService", "OrderService")
                        .WithMany("MechanicAssignments")
                        .HasForeignKey("OrderServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MechanicSpecialty", "Specialty")
                        .WithMany("MechanicAssignments")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MechanicPerson");

                    b.Navigation("OrderService");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Domain.Entities.MechanicSpecialtyAssignment", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("MechanicSpecialtyAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MechanicSpecialty", "Specialty")
                        .WithMany("MechanicSpecialtyAssignments")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Domain.Entities.Neighborhood", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.OrderService", b =>
                {
                    b.HasOne("Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("OrderServices")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("OrderServices")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceOrder");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Domain.Entities.OrderServicePart", b =>
                {
                    b.HasOne("Domain.Entities.OrderService", "OrderService")
                        .WithMany("OrderServiceParts")
                        .HasForeignKey("OrderServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Part", "Part")
                        .WithMany("OrderServiceParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderService");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Domain.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("Domain.Entities.User", "ChangedByUser")
                        .WithMany("OrderStatusHistories")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OrderStatus", "NewOrderStatus")
                        .WithMany("NewOrderStatusHistories")
                        .HasForeignKey("NewOrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OrderStatus", "PreviousOrderStatus")
                        .WithMany("PreviousOrderStatusHistories")
                        .HasForeignKey("PreviousOrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("OrderStatusHistories")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("NewOrderStatus");

                    b.Navigation("PreviousOrderStatus");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Domain.Entities.Part", b =>
                {
                    b.HasOne("Domain.Entities.PartBrand", "PartBrand")
                        .WithMany("Parts")
                        .HasForeignKey("PartBrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.PartCategory", "PartCategory")
                        .WithMany("Parts")
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartBrand");

                    b.Navigation("PartCategory");
                });

            modelBuilder.Entity("Domain.Entities.PartPurchase", b =>
                {
                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany("PartPurchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.PartPurchaseDetail", b =>
                {
                    b.HasOne("Domain.Entities.Part", "Part")
                        .WithMany("PartPurchaseDetails")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PartPurchase", "PartPurchase")
                        .WithMany("PartPurchaseDetails")
                        .HasForeignKey("PartPurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("PartPurchase");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("Domain.Entities.PaymentCard", b =>
                {
                    b.HasOne("Domain.Entities.CardType", "CardType")
                        .WithMany("PaymentCards")
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Payment", "Payment")
                        .WithOne("PaymentCard")
                        .HasForeignKey("Domain.Entities.PaymentCard", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardType");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.HasOne("Domain.Entities.Address", "Address")
                        .WithMany("Persons")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.DocumentType", "DocumentType")
                        .WithMany("Persons")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Gender", "Gender")
                        .WithMany("Persons")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("DocumentType");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Domain.Entities.PersonEmail", b =>
                {
                    b.HasOne("Domain.Entities.EmailDomain", "EmailDomain")
                        .WithMany("PersonEmails")
                        .HasForeignKey("EmailDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("PersonEmails")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmailDomain");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.PersonPhone", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("PersonPhones")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("PersonPhones")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.PersonRole", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("PersonRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("PersonRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.ServiceOrder", b =>
                {
                    b.HasOne("Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Domain.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Domain.Entities.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("Domain.Entities.VehicleEntryInventory", b =>
                {
                    b.HasOne("Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithOne("VehicleEntryInventory")
                        .HasForeignKey("Domain.Entities.VehicleEntryInventory", "ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Domain.Entities.VehicleModel", b =>
                {
                    b.HasOne("Domain.Entities.VehicleBrand", "Brand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Domain.Entities.VehicleOwnerHistory", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("VehicleOwnerHistories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleOwnerHistories")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Domain.Entities.AuditActionType", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("Domain.Entities.CardType", b =>
                {
                    b.Navigation("PaymentCards");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("PersonPhones");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Entities.DocumentType", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Domain.Entities.EmailDomain", b =>
                {
                    b.Navigation("PersonEmails");
                });

            modelBuilder.Entity("Domain.Entities.Gender", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceStatus", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Domain.Entities.MechanicSpecialty", b =>
                {
                    b.Navigation("MechanicAssignments");

                    b.Navigation("MechanicSpecialtyAssignments");
                });

            modelBuilder.Entity("Domain.Entities.Neighborhood", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Domain.Entities.OrderService", b =>
                {
                    b.Navigation("MechanicAssignments");

                    b.Navigation("OrderServiceParts");
                });

            modelBuilder.Entity("Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("NewOrderStatusHistories");

                    b.Navigation("PreviousOrderStatusHistories");

                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("Domain.Entities.Part", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("OrderServiceParts");

                    b.Navigation("PartPurchaseDetails");
                });

            modelBuilder.Entity("Domain.Entities.PartBrand", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Domain.Entities.PartCategory", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Domain.Entities.PartPurchase", b =>
                {
                    b.Navigation("PartPurchaseDetails");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Navigation("PaymentCard");
                });

            modelBuilder.Entity("Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Navigation("MechanicAssignments");

                    b.Navigation("MechanicSpecialtyAssignments");

                    b.Navigation("PersonEmails");

                    b.Navigation("PersonPhones");

                    b.Navigation("PersonRoles");

                    b.Navigation("User");

                    b.Navigation("VehicleOwnerHistories");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("PersonRoles");
                });

            modelBuilder.Entity("Domain.Entities.ServiceOrder", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("OrderServices");

                    b.Navigation("OrderStatusHistories");

                    b.Navigation("VehicleEntryInventory");
                });

            modelBuilder.Entity("Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("Domain.Entities.StreetType", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.Navigation("PartPurchases");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("OrderStatusHistories");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ServiceOrders");

                    b.Navigation("VehicleOwnerHistories");
                });

            modelBuilder.Entity("Domain.Entities.VehicleBrand", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("Domain.Entities.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Domain.Entities.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
